# Use Docker file from https://hub.docker.com/r/runmymind/docker-android-sdk
# Last docker plugin version can be found here:
# https://github.com/buildkite-plugins/docker-buildkite-plugin/releases

# Build debug version of the Riot application, from the develop branch and the features branches, with the develop branch of the matrix SDK

steps:
  - label: "Assemble GPlay Debug version"
    agents:
        # We use a medium sized instance instead of the normal small ones because
        # gradle build is long
        queue: "medium"
    commands:
      - "./set_debug_env.sh"
      - "./gradlew clean assembleAppDebug --stacktrace --info"
    artifact_paths:
      - "vector/build/outputs/apk/app/debug/*.apk"
    branches: "develop feature/*"
    plugins:
    - docker#v3.1.0:
          image: "runmymind/docker-android-sdk"

  - label: "Assemble FDroid Debug version"
    agents:
        # We use a medium sized instance instead of the normal small ones because
        # gradle build is long
        queue: "medium"
    commands:
      - "./set_debug_env.sh"
      - "./gradlew clean assembleAppfdroidDebug --stacktrace --info"
    artifact_paths:
      - "vector/build/outputs/apk/appfdroid/debug/*.apk"
    branches: "develop feature/*"
    plugins:
    - docker#v3.1.0:
          image: "runmymind/docker-android-sdk"

  - label: "Build Google Play unsigned APK"
    agents:
        # We use a medium sized instance instead of the normal small ones because
        # gradle build is long
        queue: "medium"
    commands:
      - "./gradlew clean assembleAppRelease --stacktrace --info"
    artifact_paths:
      - "vector/build/outputs/apk/app/release/*.apk"
    branches: "master"
    plugins:
    - docker#v3.1.0:
          image: "runmymind/docker-android-sdk"

# Code quality

  - label: "Code quality"
    agents:
        # We use a medium sized instance instead of the normal small ones because
        # gradle build is long
        queue: "medium"
    commands:
      - "./tools/check/check_code_quality.sh"
      - "./set_debug_env.sh"
      - "./gradlew clean lintAppfdroidRelease --stacktrace --info"
      - "./gradlew clean lintAppRelease --stacktrace --info"
    plugins:
      - docker#v3.1.0:
          image: "runmymind/docker-android-sdk"
